const { generateSW } = require('workbox-build')

const swDest = 'build/sw.js'
generateSW({
  swDest,
  globDirectory: 'build',
  globPatterns: [
    '**/*.{js,css,html,png,json,ico,xml,svg}'
  ],
  globIgnores: [
    '**/service-worker.js', // Ignore default service worker generated by react-scripts
    '**/precache-manifest.*.js'
  ]
}).then(({ count, size }) => {
  console.log(`Generated ${swDest}, which will precache ${count} files, totaling ${size} bytes.`)
})
